Metrics:
  Enabled: false

Lint/UnneededSplatExpansion:
  Enabled: false

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/ParallelAssignment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
