sudo: false
language: ruby
after_script:
  - cane
  - yard stats --list-undoc
os:
  - linux
  - osx
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
  - rbx
  - rbx-head
matrix:
  allow_failures:
    - os: osx
    - rvm: ruby-head
    - rvm: rbx
    - rvm: rbx-head
