sudo: false
language: ruby
after_script:
  - cane --style-exclude 'spec/**/*.rb'
  - yard stats --list-undoc
os:
  - linux
  - osx
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
  - rbx
  - rbx-head
matrix:
  allow_failures:
    - os: osx
    - rvm: ruby-head
    - rvm: rbx
    - rvm: rbx-head
